name: contacts_phone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.1
  flutter_slidable: ^4.0.3
  easy_localization: ^3.0.8
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  flutter_multi_formatter: ^2.13.10
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  auto_size_text: ^3.0.0
  azlistview: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets: 
    - assets/pictures/
    - assets/translations/
